// Package declaration for test runner classes
package testRunner;

import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;

/**
 * The FailedScenarioRunner class is responsible for executing only the scenarios
 * that previously failed during test execution.
 *
 * It uses the rerun file (failed_scenarios.txt) generated by the main TestRunner
 * to selectively rerun failed test cases and produce fresh reports.
 */
@CucumberOptions(
        features = "@target/failed_scenarios.txt", // Path to rerun file containing failed scenarios
        glue = "stepDefinitions",                  // Location of step definition bindings
        plugin = {
                "pretty",                                      // Clean readable console output
                "html:target/failed-cucumber-reports.html",    // HTML report for rerun
                "json:target/failed-cucumber.json"             // JSON report for integration or analytics
        },
        monochrome = true // Enables clean console output without unnecessary characters
)
public class FailedScenarioRunner extends AbstractTestNGCucumberTests {
}
